Update Investment Application Logic
pitt-crc/bank pull request #197
Opened 2022-08-15 20:50 UTC by Comeani

Addresses: 

#189 
- Use a combination of `datetime.timedelta` and `dateutil.relativedelta` to calculate start/end dates from months. Corresponding change in proposals.
- Change `num_inv` and `repeats` to `disbursements` for clarity. 

#190
 
#193

2022-08-19 14:03 UTC, djperrefort requested changes

2022-08-19 14:03 UTC, djperrefort commented on bank/account_logic.py
> +        if not (start or end):
These two lines aren't necessary. I see what you are trying to accomplish, but it's not an uncommon design for methods like this to just exit silently if there is nothing to be done. It makes it easier when building higher-level, dynamic logic.

2022-08-19 14:03 UTC, djperrefort commented on bank/account_logic.py
> +        if (start and end) and start > end:
Use `>=`

2022-08-19 14:21 UTC, Comeani commented on bank/account_logic.py
> +            LOG.info('Created proposal %d for %s', new_proposal.id, self._account_name)
Ah okay, pylint was giving me some grief about logging and fstring interpolation, but I'm still not quite sure if it's a big deal and it's easy to switch back.

2022-08-19 14:26 UTC, Comeani commented on bank/cli.py
> +            type=lambda N: (int(N) > 0) and int(N),
Good catch, I suppose the validation of the actual value of `num_inv` can be moved to the app logic.

2022-08-19 20:54 UTC, Comeani commented on bank/cli.py
> +            type=lambda date: cls.valid_date(date),
I didn't realized the function is just applied to the argument [if you don't provide input](https://docs.python.org/3/library/argparse.html#type:~:text=User%20defined%20functions%20can%20be%20used%20as%20well%3A). Fixed.

2022-08-19 20:55 UTC, Comeani commented on bank/cli.py
> +            raise BadDateFormatError(f'The provided date {date_string} is not in the correct format.')
Removing because lambdas are not being used anymore.

2022-08-19 21:32 UTC, Comeani commented on bank/cli.py
> +            metavar=f'{settings.date_format}',
The way it ends up looking is something like `--start %m/%d/%y`. I'm not sure how to convert that to "MM/DD/YY" from that format without hardcoding it. It's just a placeholder so I may just switch it to DATE.

2022-08-19 21:40 UTC, Comeani commented on bank/cli.py
> +            type=lambda N: (int(N) > 0) and int(N),
There are other variables that need to not be negative when supplied so I think I might do something similar to how I handled dates.

2022-08-19 21:47 UTC, Comeani commented on bank/account_logic.py
> +        if not (start or end):
Would it be fair to just `return` and print nothing changed? I'd like to prevent confusion for the user over whether or not calling the command from the command line did anything.

2022-08-23 20:24 UTC, Comeani commented
@djperrefort Changes since your review address items you brought up, as well as some adjustments/additions due to having done some more testing. I'll do a quick scan through the changes to see if there's anything I have questions about, but otherwise this should be good to merge.

2022-08-25 16:21 UTC, djperrefort commented on bank/account_logic.py
> +        if not (start or end):
Confirmation isn't necessary. Either way, the command is doing something. Whether or not that something results in a changed DB state is irrelevant so long as the final state reflects the new dates.

If the function exits silently the user will correctly assume the dates in the proposal are the same as the values they passed. How the function works under the hood, including whether the DB was modified, isn't something the user should need to think about (this is the principle of abstraction with a little principle of least surprise mixed in).

2022-08-26 14:20 UTC, Comeani commented on bank/account_logic.py
> +            active_inv_id_query = select(Investment.id) \
Will come back around to this another time if it's okay where it is for now.

2022-08-26 14:28 UTC, merged