Updated proposal services
pitt-crc/bank pull request #201
Opened 2022-08-19 05:38 UTC by chnixi

Adapted create_proposal, modify_proposal, add_sus, subtract_sus in account_logic.py as shown in the UML diagram of the architecture file. Changed the name "kwargs" to "clusters_sus" to make it sound more descriptive. Added boolean "all_clusters" variable, which is however not used yet.

2022-08-19 14:07 UTC, djperrefort requested changes
Only a few minor comments. Otherwise looks good.

2022-08-19 14:07 UTC, djperrefort commented on bank/account_logic.py
> +
Drop trailing whitespace (Use a linter)

2022-08-19 14:07 UTC, djperrefort commented on bank/account_logic.py
> +        if (start and end) and start > end:
Use `>=`.

2022-08-19 21:09 UTC, chnixi commented on bank/account_logic.py
> +
My bad. Forgot how massively sensitive Python is to indentation, making it unfriendly for a pure plain text editor.

2022-08-19 21:10 UTC, chnixi commented on bank/account_logic.py
> +        if (start and end) and start > end:
Fixed.

2022-08-19 22:16 UTC, djperrefort approved these changes

2022-09-07 15:23 UTC, Comeani requested changes
Notes to self after taking a pass through recent changes

2022-09-07 15:23 UTC, Comeani commented on bank/account_logic.py
> +            all_clusters: Specifies if all clusters are affected
I think all_clusters will be encapsulated in `**cluster_sus`, we'll want to include some conditional logic here for making sure `cluster_sus` is updated from `{all_clusters:SUS}` to `{SMP:SUS, MPI:SUS, GPU:SUS ... }`. The behavior should probably be to only apply the `all_clusters` value if it's provided. ex. `--all_clusters 100 --SMP 150` -> `--all_clusters 100` only.

2022-09-07 15:23 UTC, Comeani commented on bank/account_logic.py
> +            all_clusters: Specifies if all clusters are affected
Perhaps we could do this in `_verify_cluster_values`, having it update `**cluster_sus` with it's return value.

2022-09-07 15:23 UTC, Comeani commented on bank/account_logic.py
> +        self._verify_cluster_values(**clusters_sus)
See comment above about all_clusters

2022-09-07 15:23 UTC, Comeani commented on bank/account_logic.py
> +            end: Optional[date] = date.today() + relativedelta(years=1),
Change this to `None` and do something below like `end = end or (start + relativedelta(years=1))`, similar adjustment to other functions that take optional start/end

2022-09-07 15:23 UTC, Comeani commented on bank/cli.py
> +
extra line here

2022-09-07 15:23 UTC, Comeani commented on bank/settings.py
> +non_existent_account = 'dummy'
testing with an instance of https://github.com/giovtorres/slurm-docker-cluster until our environments have some test accounts in the DB

2022-09-07 15:23 UTC, Comeani commented on tests/account_logic/test_ProposalServices.py
> +    def setUp(self) -> None:
change to `test_error_on_non_existent_account`

2022-09-07 15:23 UTC, Comeani commented on tests/account_logic/test_ProposalServices.py
> +            self.account.modify_date(end=DAY_AFTER_TOMORROW)
Double check that I didn't remove EOF newlines elsewhere...

2022-09-08 13:37 UTC, Comeani commented on bank/account_logic.py
> +            all_clusters: Specifies if all clusters are affected
Realizing my explanation above isn't quite how it should work, we want the SU amount specified for `--all_clusters` available across **any** of the clusters, not awarded to each of them. It's also possible someone might want to award to a specific cluster **and** give floating units (that are not an investment) in a single create/add/subtract call. Resolving this for now, and we'll consider how it needs to be interacted with in locking with `update_account_status`

2022-09-13 04:21 UTC, merged